.SECONDEXPANSION:

test_desc.o: $$(_modobj_libscalapackfx_module)
test_desc.o = test_desc.o $($(_modobj_libscalapackfx_module))

test_common.o: $$(_modobj_scalapackfx_module) $$(_modobj_blacsfx_module) $$(_modobj_scalapackfx_tools_module)
test_common.o = test_common.o $($(_modobj_scalapackfx_module)) $($(_modobj_blacsfx_module)) $($(_modobj_scalapackfx_tools_module))
_modobj_test_common_module = test_common.o

test_psyr_pher.o: $$(_modobj_libscalapackfx_module) $$(_modobj_test_common_module)
test_psyr_pher.o = test_psyr_pher.o $($(_modobj_libscalapackfx_module)) $($(_modobj_test_common_module))

test_subgrids.o: $$(_modobj_libscalapackfx_module)
test_subgrids.o = test_subgrids.o $($(_modobj_libscalapackfx_module))

test_diag.o: $$(_modobj_libscalapackfx_module) $$(_modobj_test_common_module)
test_diag.o = test_diag.o $($(_modobj_libscalapackfx_module)) $($(_modobj_test_common_module))

