.SECONDEXPANSION:

blacs.m4: common.m4
blacs.m4 = $(common.m4)

pblasfx.o: $$(_modobj_pblas_module) $$(_modobj_scalapackfx_common_module) pblasfx.m4
pblasfx.o = pblasfx.o $($(_modobj_pblas_module)) $($(_modobj_scalapackfx_common_module)) $(pblasfx.m4)
_modobj_pblasfx_module = pblasfx.o

scalapackfx_tools.o: $$(_modobj_scalapackfx_module) $$(_modobj_blacsfx_module) scalapackfx_tools.m4 $$(_modobj_linecomm_module) $$(_modobj_scalapackfx_common_module)
scalapackfx_tools.o = scalapackfx_tools.o $($(_modobj_scalapackfx_module)) $($(_modobj_blacsfx_module)) $(scalapackfx_tools.m4) $($(_modobj_linecomm_module)) $($(_modobj_scalapackfx_common_module))
_modobj_scalapackfx_tools_module = scalapackfx_tools.o

pblas.o: $$(_modobj_scalapackfx_common_module) pblas.m4
pblas.o = pblas.o $($(_modobj_scalapackfx_common_module)) $(pblas.m4)
_modobj_pblas_module = pblas.o

scalapackfx.m4: common.m4
scalapackfx.m4 = $(common.m4)

blacsgrid.m4: common.m4
blacsgrid.m4 = $(common.m4)

blacs.o: $$(_modobj_scalapackfx_common_module) blacs.m4
blacs.o = blacs.o $($(_modobj_scalapackfx_common_module)) $(blacs.m4)
_modobj_blacs_module = blacs.o

scalapack.o: $$(_modobj_scalapackfx_common_module) scalapack.m4
scalapack.o = scalapack.o $($(_modobj_scalapackfx_common_module)) $(scalapack.m4)
_modobj_scalapack_module = scalapack.o

blacsfx.o: $$(_modobj_blacs_module) $$(_modobj_blacsgrid_module) $$(_modobj_scalapackfx_common_module) blacsfx.m4
blacsfx.o = blacsfx.o $($(_modobj_blacs_module)) $($(_modobj_blacsgrid_module)) $($(_modobj_scalapackfx_common_module)) $(blacsfx.m4)
_modobj_blacsfx_module = blacsfx.o

scalapack.m4: common.m4
scalapack.m4 = $(common.m4)

pblas.m4: common.m4
pblas.m4 = $(common.m4)

blacsgrid.o: $$(_modobj_blacs_module) $$(_modobj_scalapackfx_common_module) blacsgrid.m4
blacsgrid.o = blacsgrid.o $($(_modobj_blacs_module)) $($(_modobj_scalapackfx_common_module)) $(blacsgrid.m4)
_modobj_blacsgrid_module = blacsgrid.o

linecomm.o: $$(_modobj_scalapackfx_module) $$(_modobj_blacsfx_module) linecomm.m4 $$(_modobj_scalapackfx_common_module)
linecomm.o = linecomm.o $($(_modobj_scalapackfx_module)) $($(_modobj_blacsfx_module)) $(linecomm.m4) $($(_modobj_scalapackfx_common_module))
_modobj_linecomm_module = linecomm.o

libscalapackfx.o: $$(_modobj_scalapackfx_module) $$(_modobj_blacsfx_module) $$(_modobj_scalapackfx_tools_module) $$(_modobj_pblasfx_module)
libscalapackfx.o = libscalapackfx.o $($(_modobj_scalapackfx_module)) $($(_modobj_blacsfx_module)) $($(_modobj_scalapackfx_tools_module)) $($(_modobj_pblasfx_module))
_modobj_libscalapackfx_module = libscalapackfx.o

linecomm.m4: $$(_modobj_iso_fortran_env) common.m4
linecomm.m4 = $($(_modobj_iso_fortran_env)) $(common.m4)

scalapackfx_common.o: scalapackfx_common.m4
scalapackfx_common.o = scalapackfx_common.o $(scalapackfx_common.m4)
_modobj_scalapackfx_common_module = scalapackfx_common.o

scalapackfx_tools.m4: common.m4
scalapackfx_tools.m4 = $(common.m4)

scalapackfx.o: $$(_modobj_blacsfx_module) $$(_modobj_scalapack_module) $$(_modobj_scalapackfx_common_module) scalapackfx.m4
scalapackfx.o = scalapackfx.o $($(_modobj_blacsfx_module)) $($(_modobj_scalapack_module)) $($(_modobj_scalapackfx_common_module)) $(scalapackfx.m4)
_modobj_scalapackfx_module = scalapackfx.o

pblasfx.m4: common.m4
pblasfx.m4 = $(common.m4)

scalapackfx_common.m4: common.m4
scalapackfx_common.m4 = $(common.m4)

blacsfx.m4: common.m4
blacsfx.m4 = $(common.m4)

